//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import UIKit
import AWSAuthCore
import AWSAuthUI

class MainViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
    
//    var booksArray: [AWSBooksQueryResponse] = []
    var booksArray: [Book] = []
    
    fileprivate let loginButton: UIBarButtonItem = UIBarButtonItem(title: nil, style: .done, target: nil, action: nil)
    
    func onSignIn (_ success: Bool) {
        // handle successful sign in
        if (success) {
            self.setupRightBarButtonItem()
        } else {
            // handle cancel operation from user
        }
    }
    @IBOutlet weak var activityView: UIView!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    
    @IBOutlet weak var mainTableView: UITableView!
    @IBOutlet weak var mainTableViewBottomConstraint: NSLayoutConstraint!
    @IBOutlet weak var currentBookView: UIView!
    @IBOutlet weak var currentBookViewHeight: NSLayoutConstraint!
    @IBOutlet weak var currentBookTitle: UILabel!
    
    @IBOutlet weak var currentPlayPauseButton: UIButton!
    @IBAction func currentPlayPauseButtonAction(_ sender: Any) {
        if AVPlayerSharedInstance.sharedInstance.isPlaying == true {
            AVPlayerSharedInstance.sharedInstance.player.pause()
            AVPlayerSharedInstance.sharedInstance.isPlaying = false
            currentPlayPauseButton.titleLabel?.text = "Play"
            currentPlayPauseButton.setTitle("Play", for: .normal)
        } else {
            AVPlayerSharedInstance.sharedInstance.player.play()
            AVPlayerSharedInstance.sharedInstance.isPlaying = true
            currentPlayPauseButton.setTitle("Pause", for: .normal)
        }
    }
    
    override func viewWillAppear(_ animated: Bool) {
        setupView()
        if self.navigationController != nil {
            let navigationController = self.navigationController!
            navigationController.navigationBar.barTintColor = UIColor.init(red: 255/255, green: 211/255, blue: 0, alpha: 1.0)
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        activityView.backgroundColor = UIColor.white
        activityIndicator.hidesWhenStopped = true
        activityIndicator.startAnimating()
        
        mainTableView.delegate = self
        mainTableView.dataSource = self
        mainTableView.rowHeight = UITableViewAutomaticDimension
        mainTableView.estimatedRowHeight = 100
        
        if self.navigationController as? UINavigationController != nil {
            let navigationController = self.navigationController as! UINavigationController
            navigationController.navigationBar.barTintColor = UIColor.init(red: 255/255, green: 211/255, blue: 0, alpha: 1.0)
        }
        
        self.setupRightBarButtonItem()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: nil, action: nil)
        
        // Default theme settings.
        navigationController!.navigationBar.backgroundColor = UIColor(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
        navigationController!.navigationBar.barTintColor = UIColor(red: 0xF5/255.0, green: 0x85/255.0, blue: 0x35/255.0, alpha: 1.0)
        navigationController!.navigationBar.tintColor = UIColor.white
        presentSignInViewController()
        
//        handleLogout()
        queryBooks()
    }
    
    func setupView() {
        // No book playing, hide currentBook player
        if AVPlayerSharedInstance.sharedInstance.book?.id == nil {
            currentBookView.isHidden = true
            currentPlayPauseButton.isHidden = true
            currentBookTitle.isHidden = true
            mainTableViewBottomConstraint.constant = -(currentBookViewHeight.constant)
        } else {
            // Book currently playing
            currentBookView.isHidden = false
            currentPlayPauseButton.isHidden = false
            currentBookTitle.isHidden = false
            
            let tap = UITapGestureRecognizer(target: self, action:  #selector (self.segueToDetail (_:)))
            currentBookView.addGestureRecognizer(tap)
            
            currentBookViewHeight.constant = 66
            mainTableViewBottomConstraint.constant = 0
            
            currentBookTitle.text = AVPlayerSharedInstance.sharedInstance.book?.title
            if AVPlayerSharedInstance.sharedInstance.isPlaying == true {
                currentPlayPauseButton.setTitle("Pause", for: .normal)
            } else {
                currentPlayPauseButton.setTitle("Play", for: .normal)
            }
            
        }
    }
    
    @objc func segueToDetail(_ sender:(UITapGestureRecognizer)) {
        let book = AVPlayerSharedInstance.sharedInstance.book
        let detailVC = storyboard?.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        detailVC.book = book
        navigationController?.pushViewController(detailVC, animated: true)
    }
    
    func queryBooks() {
        awsQueryBooks() {
            (result: [Book]) in
            self.booksArray = result
            DispatchQueue.main.async {
                self.activityView.isHidden = true
                self.activityIndicator.stopAnimating()
                self.mainTableView.reloadData()
            }
        }
    }
    
    func awsQueryBooks(completion: @escaping (_ result: [Book]) -> Void) {
        let client = AWSAllBooksQueryAPIClient.default()
        var arrayOfBooks: [Book] = []
        client.rootGet().continueWith{ (task: AWSTask) -> AnyObject? in
            if let error = task.error {
                print("Error occurred: \(error)")
                return nil
            }
            if let result = task.result {
                let mutableResults = result.mutableCopy() as! NSArray
                if mutableResults != [] {
                    var tempArray: [Book] = []
                    for book in mutableResults {
                        let bookResponse = book as! AWSBooksQueryResponse
                        let bookObject = Book.init(id: bookResponse.id, title: bookResponse.title, author: bookResponse.author, listens: bookResponse.listens, s3bookcoverlocation: bookResponse.s3bookcoverlocation, s3audiolocation: bookResponse.s3audiolocation)
                        tempArray.append(bookObject)
                    }
                    arrayOfBooks = tempArray
                    completion(arrayOfBooks)
                }
            }
            return nil
        }
    }
    
//    func pushBooksToTableView(books: Array<Any>) {
//        booksArray = []
//        for book in books {
//            let bookResponse = book as! AWSBooksQueryResponse
//            booksArray.append(bookResponse)
//        }
//        DispatchQueue.main.async {
//            self.activityView.isHidden = true
//            self.activityIndicator.stopAnimating()
//            self.mainTableView.reloadData()
//        }
//    }

    func setupRightBarButtonItem() {
            navigationItem.rightBarButtonItem = loginButton
            navigationItem.rightBarButtonItem!.target = self
            
            if (AWSSignInManager.sharedInstance().isLoggedIn) {
                navigationItem.rightBarButtonItem!.title = NSLocalizedString("Sign-Out", comment: "Label for the logout button.")
            }
    }
    
    func presentSignInViewController() {
        if !AWSSignInManager.sharedInstance().isLoggedIn {
            let config = AWSAuthUIConfiguration()
            config.enableUserPoolsUI = true
            config.canCancel = false
            AWSAuthUIViewController.presentViewController(with: self.navigationController!,
                                                          configuration: config,
                                                          completionHandler: { (provider: AWSSignInProvider, error: Error?) in
                                                            if error != nil {
                                                                print("Error occurred: \(String(describing: error))")
                                                            } else {
                                                                self.onSignIn(true)
                                                            }
            })
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell:UITableViewCell? =
            mainTableView.dequeueReusableCell(withIdentifier: "BookListCell") as? UITableViewCell
        if (cell == nil)
        {
            cell = UITableViewCell(style: UITableViewCellStyle.subtitle, reuseIdentifier: "BookListCell")
        }
        let bookItem = booksArray[indexPath.row]
        
        cell!.textLabel?.numberOfLines = 0
        cell!.textLabel?.lineBreakMode = .byWordWrapping
        
        cell!.detailTextLabel?.numberOfLines = 0
        cell!.detailTextLabel?.lineBreakMode = .byWordWrapping
        
        cell!.textLabel?.text = bookItem.title
        cell!.detailTextLabel?.text = bookItem.author
        
        cell!.setNeedsLayout()
        
        return cell!
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return booksArray.count
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        mainTableView.deselectRow(at: indexPath, animated: true)
        print("Selected \(indexPath.row)")
        let book = booksArray[indexPath.row]
        let detailVC = storyboard?.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        detailVC.book = book
        navigationController?.pushViewController(detailVC, animated: true)
    }
}

class FeatureDescriptionViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem.init(title: "Back", style: .plain, target: nil, action: nil)
    }
}
